/*
* opencl_fmm.cpp
*
*  Created on: 22 Sep 2010
*      Author: david
*/
#ifdef OPENCL

#include "opencl_fmm.h"
#include <string>

// This include pulls in the OpenCL code as a
// hex dump, generated by "xxd -i". It defines 
// two vars:
//    unsigned int opencl_fmm_kernels_cl_len;
//    unsigned char opencl_fmm_kernels_cl[];
// which are hopefully self-explanatory.
// NB: Change the opencl_fmm_kernels.cl file, then
// regenerate opencl_fmm_kernels.cl.h using xxd.
#include "opencl_fmm_kernels.cl.h"

// these are the OpenCL kernel names for the specific implementations within OpenCL
// (one does the explicit interactions only for potential and field, the other does
// second derivatives as well which is significantly more work, hence the two different
// methods so that we don't waste work.
const std::string FMM_Derivatives_Level<EvalPt>::fmm_kernel_name = "FMM_explicit_kernel";
const std::string FMM_Derivatives_Level<EvalPt>::block_results_kernel_name = "processBlockResults";
const std::string FMM_Derivatives_Level<EvalPt_2ndDerivs>::fmm_kernel_name = "FMM_explicit_kernel_2nd_derivs";
const std::string FMM_Derivatives_Level<EvalPt_2ndDerivs>::block_results_kernel_name = "processBlockResults_2nd_derivs";

#endif // endif OPENCL
